const fs=require('node:fs'),path=require('node:path'),{createRequire}=require('node:module');
const wr=createRequire(path.resolve(__dirname,'../../web/package.json'));const sharp=createRequire(wr.resolve('next/package.json'))('sharp');
const all=require('./concepts.cjs');
const svg=(x,color='#252729')=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="1024" height="1024" style="color:${color}" fill="currentColor">${x.body}</svg>`;
fs.mkdirSync(path.join(__dirname,'svg'),{recursive:true});
for(const x of all)fs.writeFileSync(path.join(__dirname,'svg',`${x.id}.svg`),svg(x));
fs.writeFileSync(path.join(__dirname,'concepts.json'),JSON.stringify(all,null,2));
const data=JSON.stringify(all).replaceAll('</','<\/');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reachard · 48 个不同方向</title><style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#252729;font:15px/1.5 Arial,'Microsoft YaHei',sans-serif}main{max-width:1440px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:28px;font-weight:500;letter-spacing:-.6px}small{color:#757b83}nav{display:flex;flex-wrap:wrap;gap:12px;padding:16px 0;border-block:1px solid #e6e8eb}label{display:flex;align-items:center;gap:8px;font-size:13px}select,button,input{font:inherit;border:1px solid #dfe1e5;background:white;color:#252729;border-radius:7px;padding:7px 10px}button{cursor:pointer}button:focus-visible,select:focus-visible{outline:3px solid #007aff;outline-offset:2px}#grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:14px;margin-top:20px}.tile{border:1px solid #e7e8eb;border-radius:12px;padding:12px}.preview{border:0;width:100%;height:140px;display:grid;place-items:center;background:var(--bg,#fff)}.preview img{width:var(--size,80px);height:var(--size,80px)}.meta{display:flex;justify-content:space-between;align-items:center;margin-top:10px}.meta span{font-size:13px}.meta button{font-size:12px;padding:3px 7px}.tile.selected{border-color:#007aff}#comparison{display:flex;gap:16px;overflow:auto;margin-top:20px}#comparison article{min-width:130px;text-align:center}#comparison .preview{height:120px}#comparison img{width:85px;height:85px}#status{color:#727981;font-size:13px}dialog{border:1px solid #e7e8eb;border-radius:16px;width:min(490px,calc(100vw - 24px));padding:22px}dialog::backdrop{background:#0008}.dhead{display:flex;justify-content:space-between;align-items:center}h2{font-size:21px;font-weight:500}.hero{display:grid;place-items:center;height:260px;background:var(--bg,#fff);border-radius:10px}.hero img{width:200px;height:200px}.sizes{display:flex;justify-content:space-around;align-items:flex-end;margin:20px 0}.sizes div{text-align:center}.sizes .sample{background:var(--bg,#fff);padding:10px}.sizes small{display:block}.actions{display:flex;gap:8px;justify-content:flex-end}.actions button:last-child{background:#007aff;color:white;border-color:#007aff}@media(max-width:600px){main{padding:16px}header{display:block}h1{font-size:23px}#grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.tile{padding:8px}.preview{height:120px}}
</style><main><header><div><small>REACHARD / DISTINCT DIRECTIONS</small><h1>48 个不同构思。</h1></div><small>点击放大 · 选择对比 · 下载 SVG</small></header><nav><label>方向 <select id="family"><option value="all">全部 48 个</option>${[...new Set(all.map(x=>x.family))].map(f=>`<option>${f}</option>`).join('')}</select></label><label>配色 <select id="color"><option value="ink">深灰 / 白底</option><option value="blue">白色 / 蓝底</option><option value="dark">白色 / 深灰底</option></select></label><label>尺寸 <select id="size"><option value="48">48px</option><option value="80" selected>80px</option><option value="104">104px</option></select></label><button id="clear">清空对比</button></nav><div id="comparison" aria-label="已选对比"></div><p id="status" role="status"></p><section id="grid"></section><dialog id="detail"><div class="dhead"><h2 id="title"></h2><button id="close">关闭</button></div><div id="hero" class="hero"></div><div id="sizes" class="sizes"></div><div class="actions"><button id="pick">加入对比</button><button id="download">下载 SVG</button></div></dialog></main><script>
const all=${data},q=s=>document.querySelector(s);let chosen=[],active=null;
function raw(x){const ink=q('#color').value==='ink'?'#252729':'#fff';return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="1024" height="1024" style="color:'+ink+'" fill="currentColor">'+x.body+'</svg>';}
function img(x,size){return '<img alt="'+x.id+' '+x.name+'" '+(size?'width="'+size+'" height="'+size+'"':'')+' src="data:image/svg+xml;charset=utf-8,'+encodeURIComponent(raw(x))+'">';}
function render(){const f=q('#family').value,items=all.filter(x=>f==='all'||x.family===f);q('#grid').innerHTML=items.map(x=>'<article class="tile '+(chosen.includes(x.id)?'selected':'')+'"><button class="preview" data-open="'+x.id+'" aria-label="放大 '+x.id+'">'+img(x)+' </button><div class="meta"><span>'+x.id+' · '+x.name+'</span><button data-pick="'+x.id+'" aria-pressed="'+chosen.includes(x.id)+'">'+(chosen.includes(x.id)?'已选':'对比')+'</button></div></article>').join('');q('#comparison').innerHTML=chosen.map(id=>{const x=all.find(x=>x.id===id);return '<article><button class="preview" data-open="'+id+'">'+img(x)+'</button><button data-pick="'+id+'">'+id+' ×</button></article>';}).join('');q('#status').textContent=items.length+' 个构思 · 已选 '+chosen.length+' / 6';}
function toggle(id){if(chosen.includes(id))chosen=chosen.filter(x=>x!==id);else if(chosen.length<6)chosen.push(id);else{q('#status').textContent='最多对比 6 个，请先移除一个。';return;}render();if(active)q('#pick').textContent=chosen.includes(active.id)?'移出对比':'加入对比';}
function detail(id){active=all.find(x=>x.id===id);q('#title').textContent=id+' · '+active.name;q('#hero').innerHTML=img(active);q('#sizes').innerHTML=[16,24,32,48].map(s=>'<div><div class="sample">'+img(active,s)+'</div><small>'+s+'px</small></div>').join('');q('#pick').textContent=chosen.includes(id)?'移出对比':'加入对比';if(!q('#detail').open)q('#detail').showModal();}
document.addEventListener('click',e=>{const o=e.target.closest('[data-open]'),p=e.target.closest('[data-pick]');if(o)detail(o.dataset.open);if(p)toggle(p.dataset.pick);});q('#family').onchange=render;q('#color').onchange=()=>{document.body.style.setProperty('--bg',q('#color').value==='ink'?'#fff':q('#color').value==='blue'?'#007aff':'#252729');render();if(q('#detail').open)detail(active.id);};q('#size').onchange=()=>document.body.style.setProperty('--size',q('#size').value+'px');q('#clear').onclick=()=>{chosen=[];render();};q('#close').onclick=()=>q('#detail').close();q('#pick').onclick=()=>toggle(active.id);q('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([raw(active)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='reachard-direction-'+active.id+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();
</script></html>`;
fs.writeFileSync(path.join(__dirname,'index.html'),html);
async function board(items,name,columns=8,cell=156){
 const width=columns*cell,height=Math.ceil(items.length/columns)*cell+80;
 // Render individual SVGs first to isolate their mask IDs.
 const pieces=await Promise.all(items.map(async(x,i)=>({input:await sharp(Buffer.from(svg(x))).resize(82,82).png().toBuffer(),left:i%columns*cell+Math.round((cell-82)/2),top:80+Math.floor(i/columns)*cell+12})));
 const labels=items.map((x,i)=>`<text x="${i%columns*cell+cell/2}" y="${80+Math.floor(i/columns)*cell+127}" text-anchor="middle" font-family="Arial,sans-serif" font-size="15" fill="#5f656c">${x.id}</text>`).join('');
 const base=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="white"/><text x="30" y="44" font-family="Arial,sans-serif" font-size="23" fill="#252729">reachard / ${items.length} distinct directions</text>${labels}</svg>`;
 await sharp(Buffer.from(base)).composite(pieces).png().toFile(path.join(__dirname,name+'.png'));
}
(async()=>{await board(all,'all-directions');await board(all.filter(x=>['01','04','07','09','13','15','16','23','25','29','30','33','37','39','44','48'].includes(x.id)),'shortlist',4,230);console.log('Generated 48 distinct SVG concepts, 2 contact sheets and interactive gallery.');})().catch(e=>{console.error(e);process.exitCode=1;});
